import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Meteors } from "./components/ui/meteors";
import "./style.css"
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      < Meteors number={20}/>
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  );
}
